import type { Metadata } from "next";
import { Manrope } from "next/font/google";
import "./globals.css";
import { BreadcrumbProvider } from "@/contexts/breadcrumb-context";
import { QueryProvider } from "@/providers/query-provider";

const manrope = Manrope({
  variable: "--font-manrope-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${manrope.variable} font-sans antialiased`}>
        <QueryProvider>
          <BreadcrumbProvider>{children}</BreadcrumbProvider>
        </QueryProvider>
      </body>
    </html>
  );
}
