import type { Metadata } from "next";
import { Manrope } from "next/font/google";
import "./globals.css";
import { BreadcrumbProvider } from "@/contexts/breadcrumb-context";
import { QueryProvider } from "@/providers/query-provider";
import { GlobalAuthGuard } from "@/components/auth/global-auth-guard";
import { Toaster } from "@/components/ui/sonner";

const manrope = Manrope({
  variable: "--font-manrope-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${manrope.variable} font-sans antialiased`}>
        <QueryProvider>
          <BreadcrumbProvider>
            <GlobalAuthGuard>{children}</GlobalAuthGuard>
          </BreadcrumbProvider>
        </QueryProvider>
        <Toaster richColors position="top-center" duration={3000} />
      </body>
    </html>
  );
}
